In [4]:
## IMPORTS

import pandas as pd
import numpy as np

In [10]:
##importing data set
df = pd.read_csv("../data/machine_failure_cleaned.csv")

# **ANALYSING, CLEANING & EDA**

ANALYSIS

In [11]:
df.head()

,product_ID,product_type,air_temperature_k,process_temperature_k,rotational_speed_rpm,torque_nm,tool_wear_min,machine_failure,tool_wear_failure,heat_dissipation_failure,power_failure,overstrain_failure,random_failure
0,H29424,H,298.4,308.9,1782.0,23.9,24,0,0,0,0,0,0
1,H29425,H,298.6,309.1,1423.0,44.3,29,0,0,0,0,0,0
2,H29432,H,298.8,309.2,1306.0,54.5,50,0,0,0,0,0,0
3,H29434,H,298.9,309.3,1375.0,42.7,58,0,0,0,0,0,0
4,H29441,H,299.1,309.4,1811.0,24.6,77,0,0,0,0,0,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1081 entries, 0 to 1080
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_ID                1081 non-null   str
 1   product_type              1081 non-null   str
 2   air_temperature_k         1075 non-null   float64
 3   process_temperature_k     1075 non-null   float64
 4   rotational_speed_rpm      1080 non-null   float64
 5   torque_nm                 1074 non-null   float64
 6   tool_wear_min             1081 non-null   int64
 7   machine_failure           1081 non-null   int64
 8   tool_wear_failure         1081 non-null   int64
 9   heat_dissipation_failure  1081 non-null   int64
 10  power_failure             1081 non-null   int64
 11  overstrain_failure        1081 non-null   int64
 12  random_failure            1081 non-null   int64
dtypes: float64(4), int64(7), str(2)
memory usage: 109.9 KB

In [13]:
df.describe()

,air_temperature_k,process_temperature_k,rotational_speed_rpm,torque_nm,tool_wear_min,machine_failure,tool_wear_failure,heat_dissipation_failure,power_failure,overstrain_failure,random_failure
count,1075.000000,1075.000000,1080.000000,1074.000000,1081.000000,1081.000000,1081.000000,1081.0,1081.000000,1081.000000,1081.0
mean,296.540837,308.288744,1539.454630,41.476164,108.653099,0.022202,0.000925,0.0,0.012951,0.009251,0.0
std,16.779376,0.976013,181.580554,29.685232,63.557417,0.147407,0.030415,0.0,0.113115,0.095779,0.0
min,-20.000000,305.700000,1168.000000,4.200000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
25%,296.800000,307.800000,1424.750000,33.200000,54.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
50%,297.500000,308.400000,1503.000000,40.100000,110.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
75%,298.100000,309.000000,1611.000000,46.475000,163.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
max,299.100000,310.200000,2874.000000,500.000000,240.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.0

In [14]:
df.shape

(1081, 13)

In [15]:
df.columns

Index(['product_ID', 'product_type', 'air_temperature_k',
       'process_temperature_k', 'rotational_speed_rpm', 'torque_nm',
       'tool_wear_min', 'machine_failure', 'tool_wear_failure',
       'heat_dissipation_failure', 'power_failure', 'overstrain_failure',
       'random_failure'],
      dtype='str')

In [16]:
## There is a huge imbalance, **MUST DO CLASS=BALANCED**

df["machine_failure"].value_counts()

machine_failure
0    1057
1      24
Name: count, dtype: int64

In [17]:
df.isnull().sum()

product_ID                  0
product_type                0
air_temperature_k           6
process_temperature_k       6
rotational_speed_rpm        1
torque_nm                   7
tool_wear_min               0
machine_failure             0
tool_wear_failure           0
heat_dissipation_failure    0
power_failure               0
overstrain_failure          0
random_failure              0
dtype: int64

CLEANING

In [18]:
## SQL handled most of the cleaning, PYTHON will deal with NULL values(simple imputer, during pipeline building) and Outliers(during EDA)

In [19]:
##REMOVING unwanted columns, product_ID is only an identifier and it has no predictive value.

df = df.drop("product_ID", axis=1)